<?xml version="1.0" encoding="utf-8"?><Database Name="MateuszThomasZad4" Class="DataClassesDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-N5DK1HC\SQLEXPRESS;Initial Catalog=MateuszThomasZad4;Integrated Security=True" SettingsObjectName="DocumentCreator.Properties.Settings" SettingsPropertyName="MateuszThomasZad4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(9) NOT NULL" CanBeNull="false" />
      <Association Name="Client_Document" Member="Documents" ThisKey="ID" OtherKey="ClientID" Type="Document" />
    </Type>
  </Table>
  <Table Name="dbo.Documents" Member="Documents">
    <Type Name="Document">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TitleNotification" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeNotificationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Client_Document" Member="Client" ThisKey="ClientID" OtherKey="ID" Type="Client" IsForeignKey="true" />
      <Association Name="Item_Document" Member="Item" ThisKey="ItemID" OtherKey="ID" Type="Item" IsForeignKey="true" />
      <Association Name="TypeNotification_Document" Member="TypeNotification" ThisKey="TypeNotificationID" OtherKey="ID" Type="TypeNotification" IsForeignKey="true" />
      <Association Name="User_Document" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(127) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(31) NOT NULL" CanBeNull="false" />
      <Association Name="Item_Document" Member="Documents" ThisKey="ID" OtherKey="ItemID" Type="Document" />
    </Type>
  </Table>
  <Table Name="dbo.Passwords" Member="Passwords">
    <Type Name="Password">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Password" Member="Password1" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Password_User" Member="Users" ThisKey="ID" OtherKey="PasswordID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.TypeNotification" Member="TypeNotifications">
    <Type Name="TypeNotification">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="TypeNotification_Document" Member="Documents" ThisKey="ID" OtherKey="TypeNotificationID" Type="Document" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Document" Member="Documents" ThisKey="ID" OtherKey="UserID" Type="Document" />
      <Association Name="Password_User" Member="Password" ThisKey="PasswordID" OtherKey="ID" Type="Password" IsForeignKey="true" />
    </Type>
  </Table>
</Database>